## To instantiate this subenv in a higher level, use this structure:
##  qvip_subenvs :
##    - { name: "<instance_name_of_subenv>", type: "standard_vip" }
uvmf:
  qvip_library:
    version: '2023.3_1'
    date: '08/18/2023:20:00'
  qvip_environments:
     "standard_vip":
        agents:
          - name: 'axi4_master_0'
            imports:
              - "mvc_pkg"
              - "mgc_axi4_v1_0_pkg"
