#!/bin/bash

LD_LIBRARY_PATH=${QUESTA_MVC_HOME}/questa_mvc_core/linux_x86_64_gcc-9.3_ius:${IUS_HOME}/tools/cdsgcc/gcc/9.3/install/lib64:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

xrun -sv -uvm -quiet -access +rwc -64bit -timescale 1ns/1ns \
    ${QUESTA_MVC_HOME}/include/questa_mvc_svapi.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv +define+MAP_PROT_ATTR ${QUESTA_MVC_HOME}/questa_mvc_src/sv/mvc_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4 ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/mgc_axi4_v1_0_pkg.sv \
    +incdir+../config_policies \
    ../config_policies/standard_vip_params_pkg.sv \
    standard_vip_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules/axi4_master.sv \
    default_clk_gen.sv \
    default_reset_gen.sv \
    hdl_standard_vip.sv \
    hvl_standard_vip.sv \
    -sv_root ${QUESTA_MVC_HOME}/questa_mvc_core/linux_x86_64_gcc-9.3_ius \
    -sv_lib libaxi4_IN_SystemVerilog_IUS_full \
    +UVM_TESTNAME=standard_vip_test_base \
    +SEQ=standard_vip_vseq_base
