#!/bin/bash

LD_LIBRARY_PATH=${QUESTA_MVC_HOME}/questa_mvc_core/linux_x86_64_gcc-9.2.0_vcs:${VCS_HOME}/gnu/linux/gcc-9.2.0/lib64:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

vcs -sverilog -ntb_opts uvm -debug_access+w -quiet  -full64 -timescale=1ns/1ns \
    -ld ${VCS_HOME}/gnu/linux/gcc-9.2.0/xbin/g++ \
    ${QUESTA_MVC_HOME}/include/questa_mvc_svapi.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv +define+MAP_PROT_ATTR ${QUESTA_MVC_HOME}/questa_mvc_src/sv/mvc_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4 ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/mgc_axi4_v1_0_pkg.sv \
    +incdir+../config_policies \
    ../config_policies/standard_vip_params_pkg.sv \
    standard_vip_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules/axi4_master.sv \
    default_clk_gen.sv \
    default_reset_gen.sv \
    hdl_standard_vip.sv \
    hvl_standard_vip.sv \
    -syslib ${QUESTA_MVC_HOME}/questa_mvc_core/linux_x86_64_gcc-9.2.0_vcs/libaxi4_IN_SystemVerilog_VCS_full.so

./simv +UVM_TESTNAME=standard_vip_test_base +SEQ=standard_vip_vseq_base
